# This file was generated by the {rix} R package v0.18.2 on 2026-04-01
# with following call:
# >rix(r_ver = "98d89b5d2a42d5f965c30ef32eee726a11357cfd",
#  > r_pkgs = c("Matrix",
#  > "TreeSummarizedExperiment",
#  > "data.table",
#  > "dplyr",
#  > "httr",
#  > "jsonlite",
#  > "mia",
#  > "rix"),
#  > system_pkgs = NULL,
#  > git_pkgs = NULL,
#  > ide = "radian",
#  > project_path = path_default_nix,
#  > overwrite = TRUE,
#  > print = FALSE)
# It uses upstream nixpkgs' revision 98d89b5d2a42d5f965c30ef32eee726a11357cfd for reproducibility purposes
# which will install R version latest-upstream.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/98d89b5d2a42d5f965c30ef32eee726a11357cfd.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      data_table
      dplyr
      httr
      jsonlite
      Matrix
      mia
      rix
      TreeSummarizedExperiment;
  };
      
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      glibcLocales
      nix
      R;
  };
 
  wrapped_pkgs = pkgs.radianWrapper.override {
    packages = [  rpkgs  ];
  };
 
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.stdenv.hostPlatform.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [ rpkgs system_packages wrapped_pkgs ];
    
  }; 
in
  {
    inherit pkgs shell;
  }
